name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test --project webkit

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    # 👉 Tambahkan ini untuk Newman
    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman API Tests with Newman
      run: |
        newman run postman/blogApp.postman_collection.json \
          -e postman/blogApp.postman_environment.json \
          --reporters cli,json \
          --reporter-json-export postman/newman-report.json

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: newman-report
        path: postman/newman-report.json
        retention-days: 30
